import express from 'express';
import loansData from '../data/loans.js';
import { exec } from 'child_process';
import util from 'util';

const execPromise = util.promisify(exec);
const JAVA_BIN = '"C:\\Program Files\\Java\\jdk-25\\bin\\java.exe"';
const WORKSPACE_ROOT = 'c:\\Users\\hp\\OneDrive\\Desktop\\workmate ai';

const router = express.Router();

// GET all loans
router.get('/', (req, res) => {
    try {
        res.json(loansData);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching loans', error: error.message });
    }
});

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const modelParamsPath = path.join(__dirname, '../ml/loan_model_params.json');
const modelParams = JSON.parse(fs.readFileSync(modelParamsPath, 'utf8'));

// POST predict loan eligibility
router.post('/predict', async (req, res) => {
    try {
        const userProfile = req.body;

        // 1. Prepare features in order
        const features = modelParams.feature_names.map((name, i) => {
            let val = parseFloat(userProfile[name] || 0);
            // Scale the value: (x - mean) / scale
            return (val - modelParams.mean[i]) / modelParams.scale[i];
        });

        // 2. Logistic Regression Calculation: sigmoid(intercept + sum(feature_i * coeff_i))
        let logit = modelParams.intercept;
        for (let i = 0; i < features.length; i++) {
            logit += features[i] * modelParams.coefficients[i];
        }
        const probability = 1 / (1 + Math.exp(-logit));

        // 3. Document list generation
        const documents = [
            "Aadhar Card (Proof of Identity)",
            "Voter ID / PAN Card",
            "Last 6 months Bank Statement"
        ];

        if (userProfile.Self_Employed === '1') {
            documents.push("Business Registration Certificate / Trade License");
            documents.push("Income Tax Returns (Last 2 years)");
        } else {
            documents.push("Last 3 months Salary Slips");
            documents.push("Form 16 / Proof of Employment");
        }

        if (userProfile.Property_Area !== undefined) {
            documents.push("Property Sales Deed / Allotment Letter");
        }

        res.json({
            probability: probability,
            eligible: probability > 0.5,
            documents: documents,
            message: "Loan eligibility prediction generated by WorkMate ML (Node.js)"
        });
    } catch (error) {
        console.error('Prediction Error:', error);
        res.status(500).json({ message: 'Error predicting loan eligibility', error: error.message });
    }
});

// GET specific loan by name
router.get('/:name', (req, res) => {
    try {
        const loanName = decodeURIComponent(req.params.name);
        const loan = loansData[loanName];

        if (!loan) {
            return res.status(404).json({ message: 'Loan not found' });
        }

        res.json({ name: loanName, ...loan });
    } catch (error) {
        res.status(500).json({ message: 'Error fetching loan', error: error.message });
    }
});

export default router;
